name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: "1.37.1"

      - name: Create .nojekyll file
        run: touch .nojekyll

      - name: Build Site
        run: |
          deno run -A -r https://deno.land/x/fresh@1.5.4/dev.ts build
          mkdir -p dist
          cp -r _fresh/* dist/ || true
          cp -r static/* dist/ || true
          cp .nojekyll dist/
          echo "jpsrobertson.github.io" > dist/CNAME
          ls -la dist

      - name: List Build Output
        run: |
          echo "Contents of dist directory:"
          ls -la dist/
          echo "Contents of current directory:"
          ls -la

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          force_orphan: true
          enable_jekyll: false
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Deploy to GitHub Pages'
